/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#3cddc7',
        'on-tertiary-container': '#000705',
        'primary-fixed': '#e1e0ff',
        primary: '#c0c1ff',
        outline: '#908fa0',
        'on-background': '#dae2fd',
        'surface-dim': '#0b1326',
        'tertiary-container': '#008678',
        'on-primary-fixed': '#07006c',
        'secondary-container': '#334282',
        'on-secondary-container': '#a2b1f9',
        tertiary: '#3cddc7',
        error: '#ffb4ab',
        'primary-container': '#8083ff',
        'surface-container-highest': '#2d3449',
        'on-secondary-fixed': '#001354',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-primary-container': '#0d0096',
        'surface-variant': '#2d3449',
        'surface-tint': '#c0c1ff',
        'on-primary': '#1000a9',
        'inverse-surface': '#dae2fd',
        'surface-container': '#171f33',
        'inverse-on-surface': '#283044',
        'on-surface': '#dae2fd',
        'on-error': '#690005',
        secondary: '#b8c4ff',
        'outline-variant': '#464554',
        'tertiary-fixed': '#62fae3',
        'surface-container-high': '#222a3d',
        'on-tertiary-fixed-variant': '#005047',
        'primary-fixed-dim': '#c0c1ff',
        'on-tertiary-fixed': '#00201c',
        'on-secondary-fixed-variant': '#334282',
        background: '#0b1326',
        'secondary-fixed-dim': '#b8c4ff',
        'surface-container-low': '#131b2e',
        'secondary-fixed': '#dde1ff',
        'error-container': '#93000a',
        'on-secondary': '#1a2b6a',
        'surface-container-lowest': '#060e20',
        'on-tertiary': '#003731',
        'on-error-container': '#ffdad6',
        surface: '#0b1326',
        'surface-bright': '#31394d',
        'inverse-primary': '#494bd6',
        'on-surface-variant': '#c7c4d7',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        sm: '0.5rem',
        md: '1rem',
        'margin-mobile': '16px',
        xl: '2.5rem',
        base: '4px',
        lg: '1.5rem',
        xs: '0.25rem',
        'margin-desktop': '48px',
      },
      fontFamily: {
        'label-caps': ['JetBrains Mono'],
        'body-md': ['Inter'],
        'data-point': ['JetBrains Mono'],
        'headline-xl': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
        'body-lg': ['Inter'],
        'headline-lg': ['Hanken Grotesk'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'data-point': ['18px', { lineHeight: '1', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
